package:
  name: bioconductor-genomation
  version: 1.2.2
source:
  fn: genomation_1.2.2.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/genomation_1.2.2.tar.gz
  md5: 05b9776d71d7d653835487787ee896d7
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biostrings >=2.38.3
    - bioconductor-bsgenome >=1.38.0
    - bioconductor-genomeinfodb >=1.6.1
    - bioconductor-genomicranges >=1.22.3
    - bioconductor-genomicalignments >=1.6.3
    - bioconductor-rsamtools >=1.22.0
    - bioconductor-rtracklayer >=1.30.1
    - bioconductor-impute >=1.40.0
    - bioconductor-iranges >=2.4.7
    - bioconductor-seqpattern >=1.2.0
    - bioconductor-s4vectors >=0.8.11
    - r
    - r-data.table
    - r-ggplot2
    - r-gridbase
    - r-matrixstats
    - r-plotrix
    - r-plyr
    - r-readr
    - r-reshape2

  run:
    - bioconductor-biostrings >=2.38.3
    - bioconductor-bsgenome >=1.38.0
    - bioconductor-genomeinfodb >=1.6.1
    - bioconductor-genomicranges >=1.22.3
    - bioconductor-genomicalignments >=1.6.3
    - bioconductor-rsamtools >=1.22.0
    - bioconductor-rtracklayer >=1.30.1
    - bioconductor-impute >=1.40.0
    - bioconductor-iranges >=2.4.7
    - bioconductor-seqpattern >=1.2.0
    - bioconductor-s4vectors >=0.8.11
    - r
    - r-data.table
    - r-ggplot2
    - r-gridbase
    - r-matrixstats
    - r-plotrix
    - r-plyr
    - r-readr
    - r-reshape2
test:
  commands:
    - '$R -e "library(''genomation'')"'
about:
  home: https://www.bioconductor.org/packages/3.3/bioc/html/genomation.html
  license: Artistic-2.0
  summary: 'A package for summary and annotation of genomic intervals.
  Users can visualize and quantify genomic intervals over pre-defined functional regions,
  such as promoters, exons, introns, etc.
  The genomic intervals represent regions with a defined chromosome position,
  which may be associated with a score, such as aligned reads from HT-seq experiments,
  TF binding sites, methylation scores, etc.
  The package can use any tabular genomic feature data
  as long as it has minimal information on the locations of genomic intervals.
  In addition, It can use BAM or BigWig files as input.'
