package:
  name: perl-xml-simple
  version: 2.20

source:
  fn: XML-Simple-2.20.tar.gz
  url: http://www.cpan.org/authors/id/G/GR/GRANTM/XML-Simple-2.20.tar.gz
  md5: 4d10964e123b76eca36678464daa63cd

build:
  number: 1

requirements:
  build:
    - perl
    - perl-xml-parser 2.44

  run:
    - perl
    - perl-xml-parser 2.44

test:
  imports:
    - XML::Simple

about:
  home: http://search.cpan.org/~grantm/XML-Simple-2.20/lib/XML/Simple.pm
  license: Perl
  summary: 'The XML::Simple module provides a simple API layer on top of an
  underlying XML parsing module (either XML::Parser or one of the SAX2
  parser modules).'
