package:
  name: pandoc
  version: 1.16.0.2

source:
  fn: 1.16.0.2.tar.gz
  url: https://github.com/jgm/pandoc/archive/1.16.0.2.tar.gz
  md5: ede21f7fc469fb8a742e640d464607aa

test:
  commands:
    - pandoc --help

requirements:
  build:
  run:

build:
  number: 1

about:
  home: http://pandoc.org/
  license: GPL
  summary: Universal markup converter
