package:
  name: rcas
  version: "0.1"

source:
  #git_url: https://github.com/BIMSBbioinfo/RCAS.git
  path: ../../

requirements:
  build:
    - python
    - bedtools ==2.24.0
    - snakemake
    - pandoc
    - r-base
    - r-rmarkdown
    - bioconductor-rtracklayer
    - r-data.table
    - bioconductor-biomart
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-org.dm.eg.db
    - bioconductor-topgo
    - r-dt
    - r-plotly
    - r-dplyr
    - bioconductor-genomicfeatures
    - bioconductor-genomation
  run:
    - python
    - bedtools ==2.24.0
    - snakemake
    - pandoc
    - r-base
    - r-rmarkdown
    - bioconductor-rtracklayer
    - r-data.table
    - bioconductor-biomart
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-org.dm.eg.db
    - bioconductor-topgo
    - r-dt
    - r-plotly
    - r-dplyr
    - bioconductor-genomicfeatures
    - bioconductor-genomation

test:
  commands:
    - RCAS -h

about:
  home: https://github.com/BIMSBbioinfo/RCAS.git
  license: MIT
  license_file: LICENSE
