package:
  name: rcas
  version: "0.1"

source:
  #git_url: https://github.com/BIMSBbioinfo/RCAS.git
  path: ../../

requirements:
  build:
    - python ==2.7.8
  run:
    - python ==2.7.8

about:
  home: https://github.com/BIMSBbioinfo/RCAS.git
  license: MIT
  license_file: LICENSE
