package:
  name: rcas
  version: "0.1"

source:
  #git_url: https://github.com/BIMSBbioinfo/RCAS.git
  path: ../../

requirements:
  build:
    - python
    - bedtools ==2.24.0
    - snakemake
    - pandoc
    - meme-suite
    - bioconductor-biomart
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-org.dm.eg.db
    - bioconductor-org.ce.eg.db
    - bioconductor-topgo
    - bioconductor-genomicfeatures
    - bioconductor-genomation
    - bioconductor-rtracklayer
    - r
    - r-dt
    - r-plotly
    - r-dplyr
    - r-rmarkdown
    - r-data.table
  run:
    - python
    - bedtools ==2.24.0
    - snakemake
    - pandoc
    - meme-suite
    - bioconductor-biomart
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-org.dm.eg.db
    - bioconductor-org.ce.eg.db
    - bioconductor-topgo
    - bioconductor-genomicfeatures
    - bioconductor-genomation
    - bioconductor-rtracklayer
    - r
    - r-dt
    - r-plotly
    - r-dplyr
    - r-rmarkdown
    - r-data.table
test:
  commands:
    - RCAS -h

about:
  home: https://github.com/BIMSBbioinfo/RCAS.git
  license: MIT
  summary: 'RNA Centric Annotation System
  that provides intuitive reports and publication ready graphics.
  RCAS takes input peak intervals in BED foramt (derived from clip-seq data)
  and automatically generates distributions of annotation features,
  detected motifs, GO-term enrichment, pathway enrichment and genomic coverage.'
